services:
  firebase:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/opt/firebase
    ports:
      - 9199:9199
      - 9099:9099
      - 9005:9005
      - 9000:9000
      - 8085:8085
      - 8080:8080
      - 5001:5001
      - 5000:5000
      - 4000:4000
    working_dir: /opt/firebase
    tty: true
    command: firebase emulators:start
  front:
    image: node:16-bullseye
    volumes:
      - ./public:/app
    working_dir: /app
    ports:
      - 5173:5173
    tty: true